# Generated by Django 5.0.6 on 2024-07-09 12:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circular',
            name='url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='url',
        ),
        migrations.AddField(
            model_name='circular',
            name='attachment',
            field=models.FileField(default=datetime.datetime(2024, 7, 9, 12, 48, 32, 618307), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(default=datetime.datetime(2024, 7, 9, 12, 48, 42, 846073), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
    ]
