# Generated by Django 5.0.6 on 2024-10-13 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='image-gallery/', validators=[django.core.validators.FileExtensionValidator(['webp', 'png', 'jpg'])])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
