# Generated by Django 5.0.6 on 2024-07-09 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_partner_about_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
