# Generated by Django 5.0.6 on 2024-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_up_title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('founders_name', models.CharField(max_length=100)),
                ('founders_email', models.EmailField(max_length=254)),
                ('founders_contact', models.CharField(max_length=10)),
                ('cofounders_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cofounders_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cofounders_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('team_size', models.PositiveIntegerField()),
                ('domain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('incubation_form_url', models.URLField()),
                ('aadhar_url', models.URLField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('start_up_title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('incorporated', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('startup_stage', models.CharField(max_length=255)),
                ('needed_support', models.CharField(max_length=255)),
                ('incubated', models.TextField()),
                ('team_size', models.PositiveIntegerField()),
                ('raised_fund_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('funding_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('pitch_deck_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReachOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
